name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  DATASET: "MLproject/train_pca.csv"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          fetch-depth: 0

      - name: Set up Git LFS
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          git lfs install
          git lfs track "mlruns/**/*.pkl"
          git add .gitattributes
          git commit -m "Add Git LFS tracking for mlruns .pkl files" || echo "No changes to commit"
          git push origin main || echo "Push failed"

      - name: Set up Python 3.12.7
        uses: actions/setup-python@v4
        with:
          python-version: "3.12.7"

      - name: Check Env
        run: |
          echo $DATASET

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install mlflow==2.22.0 pandas==2.2.3 numpy==2.2.4 scikit-learn==1.6.1 scipy==1.15.3 cloudpickle==3.1.1 psutil==6.1.0 git-lfs

      - name: Clean mlruns
        run: |
          rm -rf mlruns/ || echo "No mlruns folder to clean"

      - name: Run mlflow project
        run: |
          export MLFLOW_TRACKING_URI=file://$(pwd)/mlruns
          git lfs pull
          mlflow run ./MLproject --env-manager=local -P dataset=$DATASET --verbose

      - name: Check mlruns
        run: |
          ls -la mlruns/ || echo "mlruns folder not found"

      - name: Save mlruns to repo
        run: |
          git config --global user.name "${{ secrets.USERNAME }}"
          git config --global user.email "${{ secrets.EMAIL }}"
          git remote set-url origin https://${{ secrets.USERNAME }}:${{ secrets.ACCESS_TOKEN }}@github.com/${{ github.repository }}.git
          git lfs push --all origin main || echo "Pushing LFS files"
          git add mlruns/ .gitattributes
          git commit -m "Save mlruns from CI run" || echo "No changes to commit"
          git push origin main || echo "Push failed, check permissions or branch protection"
